# Generated by Django 5.0.1 on 2024-01-27 12:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('name', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-яёЁіІїЇ]{1,20}$', 'First letter uppercase min 2 max 20 ch')])),
                ('surname', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-яёЁіІїЇ]{1,20}$', 'First letter uppercase min 2 max 20 ch')])),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^([+]?[\\s0-9]+)?(\\d{3}|[(]?[0-9]+[)])?([-]?[\\s]?[0-9])+$', 'Phone number must be 12 digits')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(90)])),
                ('course', models.CharField(choices=[('FS', 'Fs'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], default='all_courses', max_length=11)),
                ('course_format', models.CharField(choices=[('static', 'Static'), ('online', 'Online')], default='all_formats', max_length=11)),
                ('course_type', models.CharField(choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'Vip')], default='all_types', max_length=9)),
                ('status', models.CharField(
                    choices=[('in_work', 'In Work'), ('new_order', 'New Order'), ('agree', 'Agree'),
                             ('disagree', 'Disagree'), ('dubbing', 'Dubbing')], default='new_order', max_length=12)),
                ('already_paid', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('sum', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utm', models.CharField(max_length=20, null=True)),
                ('msg', models.CharField(max_length=20, null=True)),
                ('group', models.ForeignKey(default='all_groups', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='groups.groupmodel')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='core.profilemodel')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.profilemodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.ordermodel')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ('-id',),
            },
        ),
    ]
