# Generated by Django 5.0.3 on 2024-04-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('surname', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('age', models.IntegerField(null=True)),
                ('course', models.CharField(choices=[('FS', 'Fs'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=10, null=True)),
                ('course_format', models.CharField(choices=[('static', 'Static'), ('online', 'Online')], max_length=15, null=True)),
                ('course_type', models.CharField(choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'Vip')], max_length=100, null=True)),
                ('sum', models.IntegerField(null=True)),
                ('alreadyPaid', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utm', models.CharField(max_length=100, null=True)),
                ('msg', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_work', 'In Work'), ('new_order', 'New Order'), ('agree', 'Agree'), ('disagree', 'Disagree'), ('dubbing', 'Dubbing')], max_length=15, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.profilemodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.ordermodel')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ('-id',),
            },
        ),
    ]
