# Generated by Django 5.0.3 on 2024-04-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0002_ordermodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='core.profilemodel'),
        ),
    ]
