# Generated by Django 5.0.1 on 2024-01-31 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordermodel_name_alter_ordermodel_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Phone number must be 12 digits')]),
        ),
    ]
