# Generated by Django 5.0.3 on 2024-04-24 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, null=True, validators=[django.core.validators.RegexValidator('^[a-z]{3}-\\d{4}$', 'Only special format group. For example: dec-2023')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'groups',
                'ordering': ('-id',),
            },
        ),
    ]
