# Generated by Django 5.0.1 on 2024-01-30 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(max_length=35, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]{3}-\\d{4}$', 'First letter uppercase min 2 max 20 ch')]),
        ),
    ]
