# Generated by Django 5.0.1 on 2024-01-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groupmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='name',
            new_name='groupName',
        ),
    ]
