# Generated by Django 5.0.1 on 2024-01-31 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_name_groupmodel_groupname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='groupName',
            new_name='name',
        ),
    ]
