# Generated by Django 5.0.1 on 2024-01-31 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_groupname_groupmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(max_length=35, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]{3}-\\d{4}$', 'Only special format group. For example: dec-2023')]),
        ),
    ]
